### ISSUE TITLE
links in README 404

### ISSUE THREAD

**Issue by ekalosak** [Vonage/vonage-cli#120]
after "this is a monorepo ..." at the bottom, click e.g. "CLI"

**Comment by manchuck** [comment]
@ekalosak FYI, the `2.x` branch is in beta and still in active development. It only can set (or update) the config files and generate a JWT token. 

If you update the config file to use v2, then V1 will not be able to parse it. I will create a migration guide noting this.

**Comment by ekalosak** [comment]
I'm just saying the README.md on the GitHub homepage for this repo has broken links - nothing to do with v1 vs v2 I wouldn't think?

**Comment by manchuck** [comment]
Oh yes, sorry for the confusion. The README will contain the information for V2, which is still in active development. Some devs contacted me, stating that the information in the readme was inaccurate. I just wanted to give you a heads-up.
