### ISSUE TITLE
Retail mode on my Samsung galaxy z fold 5 disable

### ISSUE THREAD

**Issue by TDizzel77** [Vonage/vonage-cli#122]

**Comment by manchuck** [comment]
@TDizzel77 Can you provide more information

**Comment by TDizzel77** [comment]
Yes what info would you like. My galaxy z fold5 is stuck in retail mode and I can't figure out how to disable it with no computer just device or chomebook

**Comment by manchuck** [comment]
@TDizzel77 I'm not sure what this has to do with the Vonage CLI. Are you trying a command and having it fail? If so can you send me an example command you are trying along with the error message you are receiving?

**Comment by manchuck** [comment]
This does not seem to be an issue with our CLI. Please feel free to reach out in our [slack](https://developer.vonage.com/en/community/slack) if you have any more questions
