### ISSUE TITLE
Provide docker images to allow use without installation

### ISSUE THREAD

**Issue by thewebface** [Vonage/vonage-cli#25]
It might be nice to provide a docker image of the cli (à la [aws cli](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html)). This would allow developers to easily use it without needing to install dependencies they may not be familiar with (i.e. npm). It would also allow testing different versions without risking breaking a working installation.

I've got it working locally as follows, if Vonage provided prebuilt images on Docker Hub (or similar), then developers would just need to create the alias to start using it, with no installation required.

Create a simple dockerfile:

```
FROM node:16-alpine
RUN npm install -g @vonage/cli@beta
ENTRYPOINT ["vonage"]
```

Build the image:

```
docker build -t vonage-cli .
```

Add an alias to your .bashrc/.zshrc to simplify calls:

```
alias vonage="docker run -ti --rm -v $HOME/.vonage-cli/config:/root/.config -v $HOME/.vonage-cli/local:/root/.local vonage-cli"
```

This also keeps all cli-specific user data together in the `~/.vonage-cli` directory.

It can then be called as normal:

```
$ vonage apps
 Name                             Id                                   Capabilities 
 ──────────────────────────────── ──────────────────────────────────── ────────────   
 test-application                 01234567-89ab-cdef-0123-456789abcdef voice
```

Plugins could be baked in if preferred, perhaps different tagged versions could provide different sets of plugins for various common use-cases.

**Comment by manchuck** [comment]
We do not have an opensource docker repository. The CLI is built to be OS agnostic anyways
