### ISSUE TITLE
CLI doesn't work under Node 13.6.0

### ISSUE THREAD

**Issue by superchilled** [Vonage/vonage-cli#32]
Installed the CLI under Node 13.6.0 with `npm install -g @vonage/cli@beta`, but when attempting to set the config received the following error: `SyntaxError: Unexpected token 'export'`

**Comment by manchuck** [comment]
@superchilled We do not support Node 13 as that is an experimental build. The earliest node we support is Node 14. I'm going to close this issue but if you have any problems in later versions of Node, you can re-open
