### ISSUE TITLE
jwt command with invalid appid still creates/outputs a jwt

### ISSUE THREAD

**Issue by superchilled** [Vonage/vonage-cli#33]
Running the `vonage jwt` command with the `app_id` flag set to an invalid app id still creates/ outputs a jwt. Not sure what the expected behaviour is here, but a possible improvement might be to check the validity of the app id first.

**Comment by kellyjandrews** [comment]
This isn't ideal, no - but it just means it's unauthenticated. We can look at adding checks like this in the future.

**Comment by manchuck** [comment]
@superchilled I cannot reproduce. can you confirm if you're still having this issue with the latest version of the CLi
