### ISSUE TITLE
Creating multiple apps from same directory over-writes vonage_app.json

### ISSUE THREAD

**Issue by superchilled** [Vonage/vonage-cli#34]
If you create multiple apps from the same directory/ file location, the `vonage_app.json` file gets over-written each time. Unsure what the intended behaviour is here, but it might be better to either concatenate new app data to the file each time, or create separate files for each app (perhaps following the same naming strategy as the .key files)

**Comment by kellyjandrews** [comment]
@superchilled this is currently as designed, but I would like to investigate how we can use either method to accomplish this. Any ideas?

**Comment by kellyjandrews** [comment]
Partly the issue is - we have to modify some things to remove the current behavior, and improve the workflows as is.  Right now, vonage_app.json can be edited manually or using the cli to create a new app. Other methods then use that file as context to run their methods without using flags

**Comment by manchuck** [comment]
No longer an issue with `2.x` as the application will ask before overriding the file
