### ISSUE TITLE
App not created when using voice_answer_http or voice_event_http

### ISSUE THREAD

**Issue by superchilled** [Vonage/vonage-cli#37]
Similar to #36, the app doesn't get created when using *either* of the `voice_answer_http` or `voice_event_http`. Tested using various combinations of these options along with various combinations of the `voice_answer_url` and `voice_event_url` options.

1. Any command which included  *either* or *both* of the `voice_answer_http` or `voice_event_http` options plus the corresponding `voice_answer_url` and `voice_event_url` options resulted in a `Creating Application... done` response, but the app not being created

2. Any command which included  *either* or *both* of the `voice_answer_http` or `voice_event_http` options but without the corresponding `voice_answer_url` and `voice_event_url` options resulted in an error response (this is probably desired behaviour), e.g.

    ```
    $ vonage apps:create 'CLI Test 16' --voice_event_http=GET
     ›   Error: --voice_event_url= must also be provided when using --voice_event_http=
    ```

3.  Any command which included **one of** the `voice_answer_url` and `voice_event_url` options but not the other, and **without** the `voice_answer_http` or `voice_event_http` options resulted in the app being created (with the methods automatically set -- `POST` in the case of `voice_event_url` and `GET` in the case of `voice_answer_url`, but also some error output, e.g.

    ```
    $ vonage apps:create 'CLI Test 17' --voice_event_url=http://mycoolsite.com/voiceevent
    Application Name: CLI Test 17
    
    Application ID: f4cb963f-1a45-43fc-a7f3-96e7fb8200c0
    
    Voice Settings
       Event Webhook:
          Address: http://mycoolsite.com/voiceevent
          HTTP Method: POST
       Answer Webhook:
        TypeError: Cannot read property 'address' of undefined
    ```

4. Using the command with **both of** the `voice_answer_url` and `voice_event_url` options but not the other, and **without** the `voice_answer_http` or `voice_event_http` options resulted in the app being created (with the methods automatically set -- `POST` in the case of `voice_event_url` and `GET` in the case of `voice_answer_url`, and the expected success output, e.g.

    ```
    $ vonage apps:create 'CLI Test 19' --voice_answer_url=http://mycoolsite.com/voiceanswer --voice_event_url=http://mycoolsite.com/voiceevent
    Creating Application... done
    Application Name: CLI Test 19
    
    Application ID: 3992c45b-3f7c-45fc-9853-6a88140bc0c2
    
    Voice Settings
       Event Webhook:
          Address: http://mycoolsite.com/voiceevent
          HTTP Method: POST
       Answer Webhook:
          Address: http://mycoolsite.com/voiceanswer
          HTTP Method: GET
    
    Public Key
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA45FwJyWWpvtH0+3B/327
    quCHGwM2RAJikPV/PgZs1kMNo+SAgVtZ2ACDMT5bualbuT+VoHgZxfVtFJ6DU1OF
    4odMEdsyU6ofBFR8FEkrO/X/qhRNtiRB3B6YHT+WZg+cRVnqysn9vZL+CU57xT9v
    I4+e3HvEjrGxijQBA2R7A0KAANGGj9OfyLKdlQQ2WQCvq9IENv4ENPcWk/KiQunV
    fl9EzLCO1l3u4KEvAWq1YZ7h0tKEwp35eYJEJJ5Oy1Qb+bcngirp8++dEIjfPSBj
    bAfkXXKQ+3H5BBvPx6dJYuAQ5Nv0dd1wAh6URI7wRvydtrDHlwi59dzOjq4OT5mN
    ZwIDAQAB
    -----END PUBLIC KEY-----
    
    
    App Files
    Vonage App File: vonage_app.json
    
    Private Key File: cli_test_19.key
    
    Improve AI: false
    ```

**Comment by kellyjandrews** [comment]
This errors now as expected in the latest beta version. 
```shell
$ vonage apps:create 'CLI Test 17' --voice_event_url=http://mycoolsite.com/voiceevent
Error: --voice_answer_url= must also be provided when using --voice_event_url=
 ›   Error: --voice_answer_url= must also be provided when using 
 ›   --voice_event_url=
```


The following works as expected - I believe the API is designed to default to those methods (it's actually equally as likely in https://github.com/Vonage/vonage-node-sdk. If we discover otherwise, this should be easily resolved. 

```shell
$ vonage apps:create 'CLI Test 19' --voice_answer_url=http://mycoolsite.com/voiceanswer --voice_event_url=http://mycoolsite.com/voiceevent 

Creating Application... done
Application Name: CLI Test 19

Application ID: 2cf85566-e3e7-4dbc-857b-488a917f6050

Voice Settings
   Event Webhook:
      Address: http://mycoolsite.com/voiceevent
      HTTP Method: POST
   Answer Webhook:
      Address: http://mycoolsite.com/voiceanswer
      HTTP Method: GET
```

**Comment by fethij** [comment]
I have the same issue as mentioned above, any solutions?

**Comment by manchuck** [comment]
@fethij, please open a new ticket and include an example of the command you are typing
