### ISSUE TITLE
CLI JWT ACL path not being decoded correctly by VAPI

### ISSUE THREAD

**Issue by abdulajet** [Vonage/vonage-cli#42]
Creating a JWT with the CLI and using it to make API calls to Voce API (VAPI) is returning a 403. 

Through trial and error, I have narrowed the issue down to this line https://github.com/Vonage/vonage-cli/blob/f6c45cf3094d072875e2033283a3b153c09adff8/packages/cli/src/commands/jwt/index.ts#L56

For some reason, calling JSON.parse on the ACL paths causes a 403 from Voice API. I got to this conclusion by removing the ACL object all together which worked, then removing the call to JSON.Parse worked too. There is nothing I can see on JWT.io that seems odd, and I even tried looking for hidden Unicode characters but no luck.

A "broken" JWT seems to work fine with the iOS Client SDK

broken jwt:
```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzU1MDYxMTksImp0aSI6IjgwMWE3OWQwLTM4YTktMTFlYy1hNmFmLTFiZTY2MzcyOGMwOCIsImFwcGxpY2F0aW9uX2lkIjoiMjFhNTkzMTktNTg0Yy00MTNiLWE3ZWItZDJiYTRjMTIyMGQwIiwiYWNsIjp7InBhdGhzIjp7Ii8qL3VzZXJzLyoqIjp7fSwiLyovY29udmVyc2F0aW9ucy8qKiI6e30sIi8qL3Nlc3Npb25zLyoqIjp7fSwiLyovZGV2aWNlcy8qKiI6e30sIi8qL2ltYWdlLyoqIjp7fSwiLyovbWVkaWEvKioiOnt9LCIvKi9hcHBsaWNhdGlvbnMvKioiOnt9LCIvKi9wdXNoLyoqIjp7fSwiLyova25vY2tpbmcvKioiOnt9LCIvKi9sZWdzLyoqIjp7fX19LCJleHAiOjE2MzU1MDYxNDA3NDl9.ugvY6geWyrXBJyz1Y9W1r960dNxlAsg9-x3ts8DXwy5NfI-RyqSzMewrj-zF3WpBXY_K3CKradsCrZp2o8dX0USyEgSIWXGmC6752-UAL9Hmz4ksvCi6VStNMfU_Okcbk81KsH2SZwhc2N_gu5spitBqU05lL0GrwuBXbQEjBYsq-JYJqjrw8UiLcvrSW1kTohmN9Bnh19Rf482DjIXLmekP3ExBh3SAYGU2TYXDQEeB2tC3JX9dZpsRcIXmDsinKcIo96mwWNLAPL8-CUFbI1wA6oWSgyTsT1pG7HBK0itRayWxTgj8mPiMrnouT9wFfLvHJBdgU6hX2ahW_60KUQ
```
![Screenshot 2021-10-29 at 12 15 39](https://user-images.githubusercontent.com/15106299/139425590-53a74323-58c5-4e21-a243-ce211a523a21.png)

working jwt:
```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzU1MDYxODAsImp0aSI6ImE0OTBiYzIwLTM4YTktMTFlYy04Yzk1LTA5NTdlNzNmNDAzMSIsImFwcGxpY2F0aW9uX2lkIjoiMjFhNTkzMTktNTg0Yy00MTNiLWE3ZWItZDJiYTRjMTIyMGQwIiwiYWNsIjoie1wicGF0aHNcIjp7XCIvKi91c2Vycy8qKlwiOnt9LFwiLyovY29udmVyc2F0aW9ucy8qKlwiOnt9LFwiLyovc2Vzc2lvbnMvKipcIjp7fSxcIi8qL2RldmljZXMvKipcIjp7fSxcIi8qL2ltYWdlLyoqXCI6e30sXCIvKi9tZWRpYS8qKlwiOnt9LFwiLyovYXBwbGljYXRpb25zLyoqXCI6e30sXCIvKi9wdXNoLyoqXCI6e30sXCIvKi9rbm9ja2luZy8qKlwiOnt9LFwiLyovbGVncy8qKlwiOnt9fX0iLCJleHAiOjE2MzU1MDYyMDE5MjJ9.gEBlu1W-kjN4JGfGtUwjUtWPlHSGoHiuqajjC1c-qNv8_3WCFhPQB-Wg-KO-SPzhPYfo5HoO8CBdSyip2GW64Y2yIllZ37U12IEK9ZIhSrGesj0ymxSWjnWR3xjRINlX5AfDNIPPI3Zw2ey7Rnx2Kd4SKqB2CSzeG4BiJAalTKVm_rwivVASqNI49-vDy9JMMWzMPi7hxf2Y9Zi279fghNpAyUIfsXqqdOMUFwLY0aOEaNwHdkdLVTa4QC_coUDIbEtQETgvWbZPmWGHIjPBpOQ91OC_XzS3PrXhZri2GPGML-xDrtei3UMAfZFtwviDyYSWGsSxAlMocEU3MgAnDg
```

![Screenshot 2021-10-29 at 12 16 33](https://user-images.githubusercontent.com/15106299/139425697-2c08372c-9358-40f4-8d56-0468eebc481c.png)

**Comment by kellyjandrews** [comment]
Ooo - this is a good one. I'll see if I can figure it out this week.
